
github:
  pr_data_repo: "team-mirai-volunteer/pr-data"
  token_env_var: "GITHUB_TOKEN"
  api_base_url: "https://api.github.com"

devin_usage:
  manual_data_input: true
  usage_history_file: "./data/usage_history.csv"
  supported_formats: ["csv", "json"]

data:
  pr_data_dir: "../pr-data/prs"
  reports_dir: "./reports"
  temp_dir: "./temp"

analysis:
  devin_patterns:
    - "devin-ai-integration[bot]"
    - "devin-ai-integration"
    - "devin"
  
  default_analysis_days: 30

api:
  retry_count: 3
  rate_limit_wait: true
  request_delay: 0.5
  timeout: 30

devin_api:
  base_url: "https://api.devin.ai"
  token_env_var: "DEVIN_API_TOKEN"
  enterprise_endpoints:
    consumption: "/enterprise/consumption"
    sessions: "/sessions"
  timeout: 30

reporting:
  daily_reports: true
  monthly_summary: true
  notifications:
    slack_webhook: ""  # オプション
    email: ""          # オプション

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/devin_stats.log"
